---
title: "Climate Risk by Census Demographic Analysis"
author: "Zach Loo"
date: "February 9, 2026"
execute: 
    warning: false
    message: false
---

```{r}
# Load packages
library(tidyverse)
library(scales)
library(wesanderson)
library(showtext)
```

```{r}
#| include: false

# # #....Step 1a: see all available ACS variables + descriptions.....
# acs_vars <- tidycensus::load_variables(year = 2023,
#                                        dataset = "acs1")

# #..............Step 1b: import race & ethnicity data.............
# race_ethnicity <- tidycensus::get_acs(
#   geography = "county",
#   survey = "acs1",
#   # NOTE: you may not end up using all these variables
#   variables = c("B01003_001", "B02001_002", "B02001_003", 
#                 "B02001_004", "B02001_005", "B02001_006",
#                 "B02001_007", "B02001_008", "B03002_012",
#                 "B03002_002"),
#   state = "CA", 
#   year = 2023) |>
#   # join variable descriptions (so we know what's what!)
#   dplyr::left_join(acs_vars, by = dplyr::join_by(variable == name)) 

# #.................Step 2: write ACS data to file.................
# readr::write_csv(race_ethnicity, here::here("data", "ACS-1yr-2023-county-race-ethnicity.csv"))
```


```{r}
# Read in written csv
race_ethnicity <- read_csv(here::here("data", "ACS-1yr-2023-county-race-ethnicity.csv")) |> 
    janitor::clean_names()

# Load nri data
nri_data <- read_csv(here::here("data", "National_Risk_Index_Counties_807384124455672111.csv")) |> 
    janitor::clean_names()
```

## Prepare for data join

```{r}
# Add county name to census data
race_ethnicity <- race_ethnicity |> 
    mutate(county_name = str_trim(str_extract(name, "[\\w\\s]+(?=\\s+County)")), .after = name)

# Filter nri to California
nri_cali <- nri_data |> 
    filter(state_name_abbreviation == "CA")
```

```{r}
# Join by county name
nri_census_joined <- left_join(nri_cali, race_ethnicity, by = 'county_name', relationship = "one-to-many")
```

## Data Wrangling

```{r}
# Select columns of interest
nri_census_select <- nri_census_joined |> 
    select(county_name, national_risk_index_score_composite, national_risk_index_rating_composite, estimate, label) |> 
    relocate(c(estimate, label), .after = county_name)
```

```{r}
# Create cleaner demographic column
nri_census_cleandem <- nri_census_select |> 
    mutate(demographic = case_when(
        str_detect(label, "White") ~ "White",
        str_detect(label, "Black") ~ "Black",
        str_detect(label, "Total:!!Hispanic") ~ "Hispanic/Latino",
        str_detect(label, "Indian") ~ "American Indian/Alaska Native",
        str_detect(label, "Asian") ~ "Asian",
        str_detect(label, "Hawaiian") ~ "Native Hawaiian/Pacific Islander",
        str_detect(label, "Other Race") ~ "Other Race",
        str_detect(label, "Two or More") ~ "2+ Races",
        str_detect(label, "Total:!!Not") ~ "Not Hispanic/Latino",
        str_detect(label, "Estimate!!Total") ~ "Total Pop"
    )) |> 

    relocate(demographic, .after = label) |> 
    select(-label)
```

Each county has one hazard score so that each demographic (in a county) has the same hazard score. How to handle?

```{r}
# Aggregate demographic & nri category
nri_categories <- nri_census_cleandem |> 
    group_by(demographic, national_risk_index_rating_composite) |> 
    summarise(dem_sum = sum(estimate)) |> # Get total of each demographic per nri category
    ungroup()
```

```{r}
# Create demographic percentage column per nri category
nri_cat_perc <- nri_categories |> 
    group_by(demographic) |> 
    mutate(dem_perc = dem_sum / sum(dem_sum)) |> 

    rename(nri_category = national_risk_index_rating_composite) |> 
    mutate(nri_category = factor(nri_category, levels = c("Very High", "Relatively High", "Relatively Moderate", "Relatively Low", "Very Low"))) |> 
    filter(!demographic %in% c("Total Pop", "Not Hispanic/Latino", NA)) 
```

```{r}
# Create descending order of demographic groups for plot
dem_order <- nri_cat_perc |> 
    filter(nri_category == "Very High") |> 
    arrange(desc(dem_perc)) |> 
    pull(demographic)
```

```{r fig.width=10, fig.height=7}
#| fig-alt: "Horizontal, stacked bar plots showing the proportion of National Risk Index Categories for each demographic group in California, the most at risk being Asian, Black, and Other Race populations."
# Add google font
font_add_google("Bitter")
showtext_auto()

ggplot(nri_cat_perc, aes(dem_perc, factor(demographic, levels = rev(dem_order)), fill = nri_category)) +
    geom_col(position = position_stack(reverse  = TRUE)) +

    # Add demographic group within each bar
    geom_text(aes(label = demographic, x = 0.01), hjust = 0, vjust = 1.05, size = 7) +

    theme_minimal(base_family = "Bitter") +

    # Change x labels to percents
    scale_x_continuous(labels = label_percent()) +

    scale_fill_manual(values = rev(wes_palette("Zissou1"))) +

    labs(x = "Percentage", 
    title = "National Risk Index Across Demographic Groups in California", subtitle = "Asian, Black, and Other Race populations are amongst the highest risk to climate hazards.",
    caption = "Data: FEMA National Risk Index (2025) & US Census Bureau American Community Survey (2023).") +

    theme(
        # Adjust legend
        legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(size = 12),

        # Adjust axes
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 13),

        plot.title = element_text(hjust= 0.5, size = 22),
        plot.subtitle = element_text(hjust= 0.5, size = 13),
        plot.caption = element_text(margin = margin(t = 10)),
        panel.grid.major = element_blank())
        
```
